apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: day5-handson
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.22
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m      # 50m → 100m
            memory: 128Mi  # 64Mi → 128Mi
          limits:
            cpu: 200m      # 100m → 200m
            memory: 256Mi  # 128Mi → 256Mi
